### ISSUE TITLE
IndexError: string index out of range    Clion

### ISSUE THREAD

**Issue by sunqi1993** [prozum/meson-cmake-wrapper#17] opened 2019-05-30 16:09 UTC
```
Traceback (most recent call last):
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/bin/mcw", line 10, in <module>
    sys.exit(main())
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/main.py", line 6, in main
    CMakeWrapper().run(sys.argv)
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/cmake.py", line 66, in run
    raise e
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/cmake.py", line 182, in generate_cmd
    self.gen_codeblocks_project()
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/cmake.py", line 466, in gen_codeblocks_project
    output = os.path.join(self.meson.build_dir, self.meson.get_target_filename(target))
  File "/home/sunqi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/mcw/meson.py", line 232, in get_target_filename
    return target['filename'][0]
IndexError: string index out of range
```

Exception target['filename'] info 

{'name': 'all', 'id': 'all', 'type': 'custom', 'filename': ''}

**Comment by overby-me** [comment] 2019-05-31 11:30
I'm closing the issue since the project will be archived. Feel free to create a fork.

**Closed as completed by overby-me** 2019-05-31 11:30 UTC

**Comment by 0x00002a** [comment] 2020-02-09 19:41
I _kind of_ fixed this issue by modifying this code (229-233 in meson.py)
```
def get_target_filename(self, target):
        if self.get_version()[1] >= 50:
            return target['filename'][0]
        else:
            return target['filename']
```
And changing it to
```
def get_target_filename(self, target):
        if self.get_version()[1] >= 50:
           # <<< CHANGED 
            if len(target['filename']) > 0 and type(target['filename']) == list:
                return target['filename'][0]
            else: return target['filename']
           # >>>
        else:
            return target['filename']
```
The above is obviously a quick patchup but it will allow CLion to 'parse' the project. However the project linked directories dont seem to work (i.e `#include <some/library/linked/file>` fails). This causes CLion's syntax checking to completely break as it doesnt seem to recognize the linked files. I don't know if this is an unrelated error or not (as I havnt got this to work without the above hack/patch) but if it is thats interesting.

The parsing error seems to come as a result of the 'all' target returned by Ninja, which contains no listed files. I don't know if this is a bug further up the parsing tree or simply a change in Ninja which has broken this, i am not familer with this project but am interested in getting involved.

Should I fork and patch this? I am not sure if the above code breaks anything hidden somewhere or if it is the cause of the above bug (CLion not recognizing linked directories).

**Comment by 0x00002a** [comment] 2020-02-09 20:06
Ok update on the above after some further testing on a second machine, on the second machine the above fix does not work and I am getting `TypeError: can only concatenate str (not "list") to str` in 
```
line 492, in gen_codeblocks_project ETree.SubElement(make_commands, 'Build', {'command': self.meson.backend.path + ' -v ' + self.meson.backend.get_target(target['name'])})
```

As ive said above I have no experience with this project and am lost as to how to fix this or where it comes from. Doing some simple debugging with print through it is throwing when processing the 'all' target with the code above, returning list even with the code below, which shouldnt be possible (unless ive messed up something) so i assume it comes from some other source. 
``` python
 try:
           return target['filename'][0]
except IndexError:
            print("FILENAME: ", target['filename'])
            return target['filename']
```

(the second print statement is catching a list returned from this method on the line before the exception is raised)

**Comment by 0x00002a** [comment] 2020-02-09 20:11
Ok final (hopefully) comment on this. 

Changing 
``` python
return target['filename']
``` 
in line 47 - ninja.py (def get_target)
to 
``` python 
return str(target['filename'])
```
Fixed this, however it has the effect i've described above with CLion not even recognising system imports (such as `#include <string>`)
